#-----------------------------------------------------#
#
# Multicur Configuration Options
# Developed by Variant__
# Documentation, FAQ, and issues can be found on our DevOps portal
# See https://dev.azure.com/variantlabs/Multicur
#
#-----------------------------------------------------#

#Multicur uses MySQL as storage, there is no local storage available at this time. You must have MySQL to use Multicur
mysql:
  # This is set to false by default, set to true and enter credentials to enable the plugin
  use: false
  username: 'multicur'
  password: 'password123'
  address: '127.0.0.1:3306'

# Here are the currency settings
# Your currency has a name, a symbol, the starting balance for new players, the display format, and options to disable player to player paying
currency:
  # Start with the currency name
  token1:
    # The symbol displayed in front of the currency
    symbol: TO1
    # How much a player will start with when they first join
    starting: "0"
    # Enable this to allow players to send the currency to each other
    pay: false