name: Multicur
version: 1.1.0
api-version: 1.17
main: ca.variantlabs.multicur.Multicur
softdepend: [PlaceholderAPI]

commands:
  currency:
    description: Main base command for player commands
    usage: /currency <balance/send> [player] [amount]
    permission: multicur.currency
    permission-message: You don't have permission to use this command!
  curadmin:
    description: Main base command for admin commands
    usage: /curadmin <balance/give/remove> <player> [amount]
    permission: multicur.admin
    permission-message: You don't have permission to use this command!
permissions:
  multicur.currency:
    description: Main base permission for player commands
    default: true
  multicur.admin:
    description: Main base permission for admin commands
    default: op